language: cpp

compiler:
    - gcc

sudo: false

branches:
  only:
    - master

env:
  global:
    - GH_REPO_NAME: blatt-7-aufgabe-1-tron
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile.in
    - GH_REPO_REF: github.com/ob-algdati-ws17/blatt-7-aufgabe-1-tron

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - test/testLibrary

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
  - coveralls --root .. -E ".*googletest-src.*" -E ".*gtest.*" -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

