language: cpp

compiler:
    - gcc

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - test/testLibrary

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
  - coveralls --root .. -E ".*googletest-src.*" -E ".*gtest.*" -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

